/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dados.DAO.DicionarioDAO;
import visao.view.JTable.CustomRenderer;
import visao.view.SRSJTree.Root;
import entity.Conceito;
import entity.Projeto;
import controle.intellisense.ParserIsr;
import java.awt.Color;
import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import visao.view.tools.Constante;
import view.tools.IJframe;

/**
 *
 * @author helcio.soares
 */
public class IsrView extends JPanel implements IJframe {

    private Projeto projeto;
    private entity.Isr t;
    private String sentencaAnterior;

    public IsrView() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SRSEDITORPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT i FROM Isr i where i.idProjeto = :pIdProjeto\norder by  i.id");
        query.setParameter("pIdProjeto", this.projeto);
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dadosArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        propositoLabel1 = new javax.swing.JLabel();
        propositoField1 = new javax.swing.JTextField();

        FormListener formListener = new FormListener();

        masterTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${de}"));
        columnBinding.setColumnName("Descrição");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dadosArmazenados}"));
        columnBinding.setColumnName("Dados armazenados");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evt) {
                if (evt.getValueIsAdjusting()) {
                    Constante.desenharArvores("");
                    return;
                }
                int selected = masterTable.getSelectedRow(); //Use getSelectedRows se vc permite seleção múltipla
                //faça algo com selected
                int row = masterTable.getSelectedRow();
                sentencaAnterior = dadosArea.getText();
                Constante.desenharArvores(sentencaAnterior);
                Editor.setTitulo(projeto.getDe() + "\\Rec. de armazenamento\\" + nomeField.getText());
                }
            });
            masterScrollPane.setViewportView(masterTable);
            if (masterTable.getColumnModel().getColumnCount() > 0) {
                masterTable.getColumnModel().getColumn(0).setMinWidth(100);
                masterTable.getColumnModel().getColumn(0).setPreferredWidth(100);
                masterTable.getColumnModel().getColumn(0).setMaxWidth(150);
                masterTable.getColumnModel().getColumn(2).setMinWidth(0);
                masterTable.getColumnModel().getColumn(2).setPreferredWidth(0);
                masterTable.getColumnModel().getColumn(2).setMaxWidth(0);
            }

            nomeLabel.setText("Nome:");

            org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), nomeField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("null");
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nomeField, org.jdesktop.beansbinding.BeanProperty.create("editable"));
            bindingGroup.addBinding(binding);

            nomeField.addFocusListener(formListener);

            dadosArea.setColumns(20);
            dadosArea.setRows(5);

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dadosArmazenados}"), dadosArea, org.jdesktop.beansbinding.BeanProperty.create("text"));
            bindingGroup.addBinding(binding);

            dadosArea.addFocusListener(formListener);
            dadosArea.addKeyListener(formListener);
            jScrollPane1.setViewportView(dadosArea);

            jLabel1.setText("Dados armazenados:");

            propositoLabel1.setText("Descrição");

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.de}"), propositoField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
            bindingGroup.addBinding(binding);

            propositoField1.addFocusListener(formListener);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeLabel)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(propositoLabel1)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(propositoField1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))))
                    .addGap(0, 0, 0))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeLabel)
                        .addComponent(propositoLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(propositoField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
            );

            bindingGroup.bind();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.FocusListener, java.awt.event.KeyListener {
            FormListener() {}
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (evt.getSource() == nomeField) {
                    IsrView.this.nomeFieldFocusGained(evt);
                }
                else if (evt.getSource() == dadosArea) {
                    IsrView.this.nomeFieldFocusGained(evt);
                }
                else if (evt.getSource() == propositoField1) {
                    IsrView.this.propositoField1nomeFieldFocusGained(evt);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (evt.getSource() == nomeField) {
                    IsrView.this.nomeFieldFocusLost(evt);
                }
            }

            public void keyPressed(java.awt.event.KeyEvent evt) {
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                if (evt.getSource() == dadosArea) {
                    IsrView.this.dadosAreaKeyReleased(evt);
                }
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
            }
        }// </editor-fold>//GEN-END:initComponents

    private void nomeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFieldFocusGained
        if (!entityManager.getTransaction().isActive()) {
            entityManager.getTransaction().begin();
        }
        if (dadosArea.getText().equals("")) {
            dadosArea.setText("- ");
        }

    }//GEN-LAST:event_nomeFieldFocusGained

    private void nomeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFieldFocusLost
    }//GEN-LAST:event_nomeFieldFocusLost

    private void dadosAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dadosAreaKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            int caret = dadosArea.getCaretPosition();
            String s1 = dadosArea.getText().substring(0, caret);
            String s2 = dadosArea.getText().substring(caret, dadosArea.getText().length());
            s1 = s1 + "- ";
            dadosArea.setText(s1 + s2);
            if (s2.trim().equals("")) {
                caret = caret + 2;
            }
            dadosArea.setCaretPosition(caret);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dadosAreaKeyReleased

    private void propositoField1nomeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_propositoField1nomeFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_propositoField1nomeFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dadosArea;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<entity.Isr> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField propositoField1;
    private javax.swing.JLabel propositoLabel1;
    private javax.persistence.Query query;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IsrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IsrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IsrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IsrView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new IsrView());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    @Override
    public void setProjeto(Projeto projeto, int idTipoTabela) {
        this.projeto = projeto;
        initComponents();
        Color bg = masterTable.getSelectionBackground();
        CustomRenderer cr = new CustomRenderer(masterTable.getDefaultRenderer(Object.class), bg);
        // masterTable.setDefaultRenderer(Object.class, cr);
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        if (masterTable.getModel().getRowCount() > 0) {
            masterTable.setRowSelectionInterval(0, 0);
        }
    }

    @Override
    public void validarSentenca() {
        try {
            entity.Isr isr = getSelectedIsr();
            ParserIsr parserIsr = new ParserIsr(projeto, isr);
            String sentenca = dadosArea.getText();
            Root raiz = parserIsr.validarAtributos(sentenca);

            if (!sentenca.equals(sentencaAnterior)) {
                Constante.arvoresSentencas.remove(sentencaAnterior);
            }
            Constante.arvoresSentencas.put(sentenca, raiz);

        } catch (Exception ex) {
            Logger.getLogger(IsrView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void incluir() {
        t = new entity.Isr();
        t.setIdProjeto(this.projeto);
        entityManager.persist(t);
        list.add(t);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }

    @Override
    public void salvar() {
        entity.Isr t1 = getSelectedIsr();
        String lemma = null;
        try {
            lemma = Constante.recuperarLemmaDaPalavra(nomeField.getText());

            t1.setNomeLemma(lemma);
            DicionarioDAO dicionarioDAO = new DicionarioDAO();
            String sinonimo = dicionarioDAO.recuperarSinonimoPorChave1(lemma, projeto);
            if (!sinonimo.isEmpty()) {
                int resultado = JOptionPane.showConfirmDialog(null, "'" + sinonimo + "' é sinonimo de '" + nomeField.getText()
                        + "', deseja utilizá-lo? \n Se não a operação será cancelada!", "Alerta!", JOptionPane.YES_NO_OPTION);
                if (resultado == JOptionPane.YES_OPTION) {
                    Conceito c = dicionarioDAO.recuperarConceitoPorLemmaNome(sinonimo, projeto.getId());
                    t1.setNome(c.getDe());
                    t1.setNomeLemma(c.getNomeLemma());
                } else {
                    return;
                }
            }

            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            JOptionPane.showMessageDialog(null, "Já existe um registro com esse nome!");
        } catch (Exception ex) {
            Logger.getLogger(IsrView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private entity.Isr getSelectedIsr() {
        int[] selected = masterTable.getSelectedRows();
        return list.get(masterTable.convertRowIndexToModel(selected[0]));
    }

    @Override
    public void refresh() {
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }

    @Override
    public void deletar() {
        int[] selected = masterTable.getSelectedRows();
        // refresh();
        masterTable.setRowSelectionInterval(selected[0], selected[0]);
        masterTable.scrollRectToVisible(masterTable.getCellRect(selected[0], 0, true));

        if (!entityManager.getTransaction().isActive()) {
            entityManager.getTransaction().begin();
        }
        entity.Isr t = list.get(masterTable.convertRowIndexToModel(selected[0]));
        try {
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar o Requisito de armazenamento " + nomeField.getText()+"?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                entityManager.remove(t);
                entityManager.getTransaction().commit();
                list.remove(t);
            } else {
                return;
            }
        } catch (javax.persistence.RollbackException e) {
            JOptionPane.showMessageDialog(null, "O registro nao pode ser deletado!");
        } catch (java.lang.IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Existem atributos do tipo '" + nomeField.getText() + "' em outros Requisitos de armazenamento!");
        }

        if (selected[0] > list.size() - 1) {
            masterTable.setRowSelectionInterval(list.size() - 1, list.size() - 1);
        } else {
            masterTable.setRowSelectionInterval(selected[0], selected[0]);

        }
    }

    @Override
    public void validarTodasSentenca() {
        validar();
    }

    private void validar() {
        for (int i = 0; i <= list.size() - 1; i++) {
            entity.Isr t1 = list.get(i);
            masterTable.setRowSelectionInterval(i, i);
            masterTable.scrollRectToVisible(masterTable.getCellRect(i, 0, true));
            validarSentenca();
        }
    }
}
